apiVersion: v1

kind: PersisitentVolumeClaim

metadata:
  name: postgres-pvc
  labels:
    type: local

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: postgres-pv